<?php

namespace MDZ\DigischoolBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
	
	final public function getMaxVotes():array {
		$query = $this->_em->createQuery('SELECT MAX(m.score) as max_score, m ' .
		'FROM MDZDigischoolBundle:Movie m');
		
		return $query->getQuery->getSingleResult();
	}
}
