<?php

namespace MDZ\DigischoolBundle\Repository;

/**
 * UserMovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMovieRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	* Get the number of choice for an User
	*
	* @param int $userId user's id
	* @return int
	*/
	final public function voteCounter(int $userId):int {
		$query = $this->_em->createQuery('SELECT count(u.user_id) FROM ' .
		'MDZDigischoolBundle:UserMovie u ' .
		'WHERE u.user_id = :id');
		$query->setParameter('id', $userId);
		
		return $query->getQuery->getSingleScalarResult();
	}
	
	/**
	* Get movies upvoted by a specific User
	*
	* @param int $userId user's id
	* @return array
	*/
	final public function getMoviesByUser(int $userId):array {
		$query = $this->_em->createQuery('SELECT m.title, m.poster ' .
		'FROM MDZDigischoolBundle:UserMovie u ' . 
		'LEFT JOIN MDZDigischoolBundle:Movie m ON u.movie_id = m.id ' .
		'WHERE u.user_id = :userid');
		$query->setParameter('userid', $userId);
		
		return $query->getResult();
	}

	/**
	* Get users that have upvoted a specific Movie
	*
	* @param int $movieId movie's id
	* @return array
	*/
	final public function getUsersByMovie(int $movieId): array {
		$query = $this->_em->createQuery('SELECT m.title, m.poster ' .
		'FROM MDZDigischoolBundle:UserMovie u ' . 
		'LEFT JOIN MDZDigischoolBundle:User m ON u.user_id = m.id ' .
		'WHERE u.movie_id = :movieid');
		$query->setParameter('movie', $movieId);
		
		return $query->getResult();
	}
}
